### PR TITLE
Drop Jenkins job for deprecated vagrant-ceph

### PR DESCRIPTION
**Pull request by colder-is-better**
`vagrant-ceph` has been deprecated in favour of `sesdev`, so there's no reason for keeping this Jenkins job arround.

### CODE REVIEW

**Comment by toabctl** [comment]
> `vagrant-ceph` has been deprecated in favour of `sesdev`, so there's no reason for keeping this Jenkins job arround.

Can you add this comment to the commit message instead of the github PR?

**Comment by kshtsk** [comment]
I missed something, why we are depricating this job?

**Comment by kshtsk** [comment]
@toabctl we deprecate the tool https://github.com/openSUSE/vagrant-ceph instead of supporting?

**Comment by toabctl** [comment]
> I missed something, why we are depricating this job?

Nobody uses vagrant-ceph. There is sesdev nowadays.

**Review by toabctl — APPROVED** [review]

**Comment by kshtsk** [comment]
> > I missed something, why we are depricating this job?
> 
> Nobody uses vagrant-ceph. There is sesdev nowadays.

before doing this, maybe one should go to openSUSE/vagrant-ceph and remove references to the jenkins first?

**Comment by colder-is-better** [comment]
@kshtsk One did.

**Comment by kshtsk** [comment]
> @kshtsk One did.

who did? which commit?

**Comment by toabctl** [comment]
@kshtsk https://github.com/openSUSE/vagrant-ceph/pull/77

**Comment by kshtsk** [comment]
> @kshtsk [openSUSE/vagrant-ceph#77](https://github.com/openSUSE/vagrant-ceph/pull/77)

thanks

**Pull request merged**
