### PR TITLE
util: change regex to match new deepsea task output 

### PR DESCRIPTION
**Pull request by smithfarm**
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
@kshtsk Please help me to understand what is needed here. I unified the orchestration running code, so a stage is just a type of orchestration. When the orchestration completes it emits a message like this:

```
orchestration ceph.stage.0 failed. Here comes journalctl!
```

Yes, this is different than what we had before :-)

**Comment by kshtsk** [comment]
> @kshtsk Please help me to understand what is needed here. I unified the orchestration running code, so a stage is just a type of orchestration. When the orchestration completes it emits a message like this:
> 
> ```
> orchestration ceph.stage.0 failed. Here comes journalctl!
> ```
> Yes, this is different than what we had before :-)

Thanks for this commit. If you have already finished the development or you have a log example, I would like to take a look at it. Probably we need to bind to teuthology tasks?

**Comment by smithfarm** [comment]
failure case is here: http://10.86.0.135/ubuntu-2018-11-06_17:29:34-deepsea:tier0-ses6---basic-openstack/251/teuthology.log

I'm still working on success case (until now I did not emit any message on success)

**Comment by smithfarm** [comment]
OK, success message is exactly the same as failure message, except it says "completed" instead of "failed".

**Pull request merged**
